class Config:
    SECRET_KEY = 'YOUR_SECRET_KEY'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///YOUR_ABSOLUTE_PATH_TO_APP_REPO'
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SENDGRID_API_KEY = 'YOUR_SENDGRID_API_KEY'
    SENDER_EMAIL = 'YOUR_SENDER_EMAIL'
